package com.javainuse.congresorest;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TablaCongreso generated by hbm2java
 */
@Entity
@Table(name = "tabla_congreso", catalog = "congreso")
public class TablaCongreso implements java.io.Serializable {

	private String idCodigoDeBarra;
	private String nombreDelProducto;
	private int iva;
	private float precioUnitario;
	private float precioUnitarioMasIva;
	private float remarcacion;
	private float remarcacionResultado;
	private float remarcacionResultadoFinal;
	private String proveedoresNombres;
	private String marcasDeProductos;
	private Date fechadeingreso;
	private int cantidadDeProductos;
	private int cantidadLimite;

	public TablaCongreso() {
	}

	public TablaCongreso(String idCodigoDeBarra, String nombreDelProducto, int iva, float precioUnitario,
			float precioUnitarioMasIva, float remarcacion, float remarcacionResultado, float remarcacionResultadoFinal,
			String proveedoresNombres, String marcasDeProductos, Date fechadeingreso, int cantidadDeProductos,
			int cantidadLimite) {
		this.idCodigoDeBarra = idCodigoDeBarra;
		this.nombreDelProducto = nombreDelProducto;
		this.iva = iva;
		this.precioUnitario = precioUnitario;
		this.precioUnitarioMasIva = precioUnitarioMasIva;
		this.remarcacion = remarcacion;
		this.remarcacionResultado = remarcacionResultado;
		this.remarcacionResultadoFinal = remarcacionResultadoFinal;
		this.proveedoresNombres = proveedoresNombres;
		this.marcasDeProductos = marcasDeProductos;
		this.fechadeingreso = fechadeingreso;
		this.cantidadDeProductos = cantidadDeProductos;
		this.cantidadLimite = cantidadLimite;
	}

	@Id

	@Column(name = "id_codigo_de_barra", unique = true, nullable = false, length = 60)
	public String getIdCodigoDeBarra() {
		return this.idCodigoDeBarra;
	}

	public void setIdCodigoDeBarra(String idCodigoDeBarra) {
		this.idCodigoDeBarra = idCodigoDeBarra;
	}

	@Column(name = "nombre_del_producto", nullable = false, length = 100)
	public String getNombreDelProducto() {
		return this.nombreDelProducto;
	}

	public void setNombreDelProducto(String nombreDelProducto) {
		this.nombreDelProducto = nombreDelProducto;
	}

	@Column(name = "iva", nullable = false)
	public int getIva() {
		return this.iva;
	}

	public void setIva(int iva) {
		this.iva = iva;
	}

	@Column(name = "precio_unitario", nullable = false, precision = 100, scale = 6)
	public float getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(float precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "precio_unitario_mas_iva", nullable = false, precision = 100, scale = 6)
	public float getPrecioUnitarioMasIva() {
		return this.precioUnitarioMasIva;
	}

	public void setPrecioUnitarioMasIva(float precioUnitarioMasIva) {
		this.precioUnitarioMasIva = precioUnitarioMasIva;
	}

	@Column(name = "remarcacion", nullable = false, precision = 22, scale = 6)
	public float getRemarcacion() {
		return this.remarcacion;
	}

	public void setRemarcacion(float remarcacion) {
		this.remarcacion = remarcacion;
	}

	@Column(name = "remarcacion_resultado", nullable = false, precision = 22, scale = 6)
	public float getRemarcacionResultado() {
		return this.remarcacionResultado;
	}

	public void setRemarcacionResultado(float remarcacionResultado) {
		this.remarcacionResultado = remarcacionResultado;
	}

	@Column(name = "remarcacion_resultado_final", nullable = false, precision = 22, scale = 6)
	public float getRemarcacionResultadoFinal() {
		return this.remarcacionResultadoFinal;
	}

	public void setRemarcacionResultadoFinal(float remarcacionResultadoFinal) {
		this.remarcacionResultadoFinal = remarcacionResultadoFinal;
	}

	@Column(name = "proveedores_nombres", nullable = false, length = 100)
	public String getProveedoresNombres() {
		return this.proveedoresNombres;
	}

	public void setProveedoresNombres(String proveedoresNombres) {
		this.proveedoresNombres = proveedoresNombres;
	}

	@Column(name = "marcas_de_productos", nullable = false, length = 100)
	public String getMarcasDeProductos() {
		return this.marcasDeProductos;
	}

	public void setMarcasDeProductos(String marcasDeProductos) {
		this.marcasDeProductos = marcasDeProductos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechadeingreso", nullable = false, length = 19)
	public Date getFechadeingreso() {
		return this.fechadeingreso;
	}

	public void setFechadeingreso(Date fechadeingreso) {
		this.fechadeingreso = fechadeingreso;
	}

	@Column(name = "cantidad_de_productos", nullable = false)
	public int getCantidadDeProductos() {
		return this.cantidadDeProductos;
	}

	public void setCantidadDeProductos(int cantidadDeProductos) {
		this.cantidadDeProductos = cantidadDeProductos;
	}

	@Column(name = "cantidad_limite", nullable = false)
	public int getCantidadLimite() {
		return this.cantidadLimite;
	}

	public void setCantidadLimite(int cantidadLimite) {
		this.cantidadLimite = cantidadLimite;
	}

}
